apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "wikibase.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wikibase.name" . }}
    helm.sh/chart: {{ include "wikibase.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wikibase.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wikibase.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: DB_SERVER
              value: {{ template "wikibase.mariadb.fullname" . }}
            - name: MW_ELASTIC_HOST
              value: "elasticsearch.svc"
            - name: MW_ELASTIC_PORT
              value: "9200"
            - name: MW_ADMIN_NAME
              value: "admin"
            - name: MW_ADMIN_PASS
              value: "adminpass"
            - name: MW_WG_SECRET_KEY
              value: "secretkey"
            - name: DB_USER
              value: "wikiuser"
            - name: DB_PASS
              value: "sqlpass"
            - name: DB_NAME
              value: "my_wiki"
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
